In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
X = iris.data

In [8]:
# X

In [6]:
y = iris.target

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from keras.utils.np_utils import to_categorical

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [9]:
y = to_categorical(y)

In [10]:
y.shape

(150, 3)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y, test_size=0.33)

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
sclar_object = MinMaxScaler()

In [15]:
sclar_object.fit(xtrain)

MinMaxScaler()

In [16]:
sclar_xtrain = sclar_object.transform(xtrain)

In [17]:
sclar_xtest = sclar_object.transform(xtest)

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [19]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(sclar_xtrain, ytrain, epochs=150, verbose=2)

Epoch 1/150
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmpxsi2m2zd.py, line 48)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: invalid syntax (tmpxsi2m2zd.py, line 48)
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
4/4 - 13s - loss: 1.0732 - accuracy: 0.3500
Epoch 2/150
4/4 - 0s - loss: 1.0668 - accuracy: 0.3800
Epoch 3/150
4/4 - 0s - loss: 1.0618 - accuracy: 0.3800
Epoch 4/150
4/4 - 0s - loss: 1.0558 - accuracy: 0.3800
Epoch 5/150
4/4 - 0s - loss: 1.0516 - accuracy: 0.3800
Epoch 6/150
4/4 - 0s - loss: 1.0465 - accuracy: 0.3800
Epoch 7/150
4/4 - 0s - loss: 1.0416 - accuracy: 0.3800
Epoch 8/15

- predicting from the created model

In [24]:
predictions = model.predict_classes(sclar_xtest)

d:\coding\py_AI_ML\MatchineLearning\venv\lib\site-packages\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [25]:
y_transformed = ytest.argmax(axis=1)

In [27]:
y_transformed

array([0, 1, 0, 1, 2, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 2, 0, 0, 2, 2, 0, 1,
       0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 2, 0, 1, 2, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 2], dtype=int64)

In [28]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [29]:
print(classification_report(y_transformed, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      0.88      0.93        16
           2       0.86      1.00      0.92        12

    accuracy                           0.96        50
   macro avg       0.95      0.96      0.95        50
weighted avg       0.97      0.96      0.96        50



In [30]:
print(accuracy_score(y_transformed, predictions))

0.96


## saving the model

In [32]:
model.save("leafmodel.h5")

### load the model

In [34]:
from keras.models import load_model

In [35]:
model2 = load_model("leafmodel.h5")

In [39]:
model2.predict_classes(sclar_xtest)

array([0, 1, 0, 1, 2, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 2, 0, 0, 2, 2, 0, 1,
       0, 2, 1, 0, 0, 2, 1, 2, 0, 0, 1, 2, 0, 1, 2, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 2], dtype=int64)